#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

if [[ -f ".venv/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source ".venv/bin/activate"
elif [[ -f "venv/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source "venv/bin/activate"
else
  echo "No virtual environment found (.venv or venv)." >&2
  exit 1
fi

# Balanced defaults for this machine profile (Intel 2c/4t, 16 GB RAM).
export FREE_LLM_PROVIDER="${FREE_LLM_PROVIDER:-ollama}"
export FORCE_FREE_LLM="${FORCE_FREE_LLM:-true}"
export FREE_THOUGHT_MODEL="${FREE_THOUGHT_MODEL:-qwen2.5:latest}"
export FREE_REVIEW_MODEL="${FREE_REVIEW_MODEL:-qwen2.5:latest}"
export FREE_ACTION_MODEL="${FREE_ACTION_MODEL:-qwen2.5:latest}"
export OLLAMA_BASE_URL="${OLLAMA_BASE_URL:-http://localhost:11434}"
export OLLAMA_AUTO_START="${OLLAMA_AUTO_START:-true}"
export OLLAMA_AUTO_START_TIMEOUT_SECONDS="${OLLAMA_AUTO_START_TIMEOUT_SECONDS:-25}"
export OLLAMA_AUTO_START_RETRY_WINDOW_SECONDS="${OLLAMA_AUTO_START_RETRY_WINDOW_SECONDS:-15}"
export OLLAMA_PROBE_TIMEOUT_SECONDS="${OLLAMA_PROBE_TIMEOUT_SECONDS:-1.5}"
export OLLAMA_TAGS_TIMEOUT_SECONDS="${OLLAMA_TAGS_TIMEOUT_SECONDS:-4}"
export OLLAMA_CHAT_TIMEOUT_SECONDS="${OLLAMA_CHAT_TIMEOUT_SECONDS:-120}"
export OLLAMA_CHAT_RETRIES="${OLLAMA_CHAT_RETRIES:-2}"
export OLLAMA_BACKOFF_SECONDS="${OLLAMA_BACKOFF_SECONDS:-8}"
export OLLAMA_NUM_PREDICT="${OLLAMA_NUM_PREDICT:-160}"
export OLLAMA_NUM_CTX="${OLLAMA_NUM_CTX:-1536}"
export OLLAMA_NUM_THREAD="${OLLAMA_NUM_THREAD:-2}"
export LOCAL_RESCUE_ENABLED="${LOCAL_RESCUE_ENABLED:-true}"
export LOCAL_SINGLE_PASS_ENABLED="${LOCAL_SINGLE_PASS_ENABLED:-true}"
export OLLAMA_SINGLE_PASS_TIMEOUT_SECONDS="${OLLAMA_SINGLE_PASS_TIMEOUT_SECONDS:-95}"
export OLLAMA_SINGLE_PASS_HARD_TIMEOUT_SECONDS="${OLLAMA_SINGLE_PASS_HARD_TIMEOUT_SECONDS:-100}"
export OLLAMA_SINGLE_PASS_RETRIES="${OLLAMA_SINGLE_PASS_RETRIES:-0}"
export OLLAMA_SINGLE_PASS_NUM_PREDICT="${OLLAMA_SINGLE_PASS_NUM_PREDICT:-96}"
export HUGGINGFACE_API_KEY="${HUGGINGFACE_API_KEY:-}"
export HF_TOKEN="${HF_TOKEN:-}"
export HUGGINGFACE_MODEL="${HUGGINGFACE_MODEL:-Qwen/Qwen2.5-7B-Instruct}"
export HUGGINGFACE_BASE_URL="${HUGGINGFACE_BASE_URL:-https://router.huggingface.co/v1}"
export HUGGINGFACE_CHAT_TIMEOUT_SECONDS="${HUGGINGFACE_CHAT_TIMEOUT_SECONDS:-80}"
export HUGGINGFACE_MAX_TOKENS="${HUGGINGFACE_MAX_TOKENS:-220}"
export HUGGINGFACE_TEMPERATURE="${HUGGINGFACE_TEMPERATURE:-0.2}"

export THERMAL_MONITOR_ENABLED="${THERMAL_MONITOR_ENABLED:-true}"
export THERMAL_POLL_INTERVAL_SECONDS="${THERMAL_POLL_INTERVAL_SECONDS:-1.5}"
export THERMAL_WARNING_C="${THERMAL_WARNING_C:-72}"
export THERMAL_CRITICAL_C="${THERMAL_CRITICAL_C:-79}"
export THERMAL_COOLDOWN_WARN_SECONDS="${THERMAL_COOLDOWN_WARN_SECONDS:-1.2}"
export THERMAL_COOLDOWN_CRITICAL_SECONDS="${THERMAL_COOLDOWN_CRITICAL_SECONDS:-3.2}"
export THERMAL_TIMEOUT_SCALE_WARNING="${THERMAL_TIMEOUT_SCALE_WARNING:-0.95}"
export THERMAL_TIMEOUT_SCALE_CRITICAL="${THERMAL_TIMEOUT_SCALE_CRITICAL:-0.7}"
export THERMAL_TIMEOUT_MIN_SECONDS="${THERMAL_TIMEOUT_MIN_SECONDS:-10}"

MODE="${1:-agent}"

echo "Mode: ${MODE}"
echo "Ollama: ${OLLAMA_BASE_URL}"
echo "Thermal: warn=${THERMAL_WARNING_C}C critical=${THERMAL_CRITICAL_C}C"

case "$MODE" in
  agent)
    exec python src/agent.py
    ;;
  api)
    exec uvicorn src.api_server:app --host 127.0.0.1 --port 8000 --reload
    ;;
  *)
    echo "Usage: ./run_balanced.sh [agent|api]" >&2
    exit 2
    ;;
esac
